### ISSUE TITLE
payload manifest is created with backslashes in windows

### ISSUE THREAD

**Issue by atomotic** [joehand/bagit-fs#2]
from [bagit spec](https://tools.ietf.org/html/draft-kunze-bagit-14#section-2.1.3): 

```
Each line of a payload manifest file MUST be of the form:

   CHECKSUM FILENAME
...
...
The slash
   character ('/') MUST be used as a path separator in FILENAME.
```

the use of `path.join()` in windows write a manifest containing backslashes ('\\') instead of ('/')

https://github.com/joehand/bagit-fs/blob/master/index.js#L141

**Comment by joehand** [comment]
Thanks! Released in 1.1.1. 

The `path.join()` is needed to write the file for windows, but I updated the string that is written to the manifest to replace path separators with `/`.
